INSERT INTO hockey_protocol.player_position (id, full_name, short_name) VALUES (1, 'левый нападающий', 'ЛН');
INSERT INTO hockey_protocol.player_position (id, full_name, short_name) VALUES (2, 'правый нападающий', 'ПрН');
INSERT INTO hockey_protocol.player_position (id, full_name, short_name) VALUES (3, 'центральный нападающий', 'ЦН');
INSERT INTO hockey_protocol.player_position (id, full_name, short_name) VALUES (4, 'левый защитник', 'ЛЗ');
INSERT INTO hockey_protocol.player_position (id, full_name, short_name) VALUES (5, 'правый защитник', 'ПЗ');
INSERT INTO hockey_protocol.player_position (id, full_name, short_name) VALUES (6, 'левый нападающий', 'ЛН');
INSERT INTO hockey_protocol.player_position (id, full_name, short_name) VALUES (7, 'правый нападающий', 'ПрН');
INSERT INTO hockey_protocol.player_position (id, full_name, short_name) VALUES (8, 'центральный нападающий', 'ЦН');
INSERT INTO hockey_protocol.player_position (id, full_name, short_name) VALUES (9, 'левый защитник', 'ЛЗ');
INSERT INTO hockey_protocol.player_position (id, full_name, short_name) VALUES (10, 'правый защитник', 'ПЗ');
INSERT INTO hockey_protocol.player_position (id, full_name, short_name) VALUES (11, 'вратарь', 'В');